version: "3.9"
services:
  frontend:
    container_name: gy_frontend
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

  backend:
    container_name: gy_backend
    build:
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  database:
    build:
      context: ./backend
      dockerfile: ../docker/database/Dockerfile
      args:
        uid: 1000
    container_name: gy_mysql
    image: mysql:8.0.32
    # Uncomment below when on Mac M1
    # platform: linux/arm64/v8
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    env_file:
      - ./backend/.env

  webserver:
    container_name: gy_web
    build:
      context: ./backend
      dockerfile: ../docker/webserver/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./docker/webserver:/var/www/html
      - ./backend:/app/backend

volumes:
  mysql_data:
