version: "3.9"
services:
  webserver:
    container_name: gy_web
    build:
      context: ./docker/webserver
    ports:
      - "80:80"
    depends_on:
      - backend
      - database
    volumes:
      - ./docker/webserver:/var/www/html
      - ./backend:/app/backend
    user: www-data

  frontend:
    container_name: gy_frontend
    build:
      context: ./docker/frontend
    networks:
      - frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    stop_grace_period: 0s

  backend:
    container_name: gy_backend
    build:
      context: ./docker/backend
    networks:
      - backend
    depends_on:
      - database
    environment:
      COMPOSER_MEMORY_LIMIT: -1
      MESSENGER_TRANSPORT_DSN: doctrine://default?auto_setup=0
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  database:
    platform: linux/x86_64
    build:
      context: ./docker/database
      args:
        uid: 1000
    container_name: gy_mysql
    image: mysql:8.0.32
    # Uncomment below when on Mac M1
    # platform: linux/arm64/v8
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - backend
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Europe/London
    ports:
      - "3306:3306"
    env_file:
      - ./backend/.env

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

volumes:
  mysql_data:
