version: "3.9"

services:
    mysql:
        container_name: gy_mysql
        image: mysql:8.0.33
        platform: linux/x86_64
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "gymek_data:/var/lib/mysql"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
        networks:
            - backend_app
    php:
        container_name: gy_php
        build:
            context: ./docker/php
            args:
                TIMEZONE: ${TIMEZONE}
        depends_on:
            - mysql
        volumes:
            - ../:/var/www/backend:cached
            - backend_var:/var/www/backend/var
            - backend_vendor:/var/www/backend/vendor
        restart: on-failure
        ports:
            - "9000:9000"
        networks:
            - backend_app
    nginx:
        container_name: gy_nginx
        build:
            context: ./docker/nginx
        volumes:
            - ../:/var/www/backend:cached
            - backend_var:/var/www/var
            - backend_vendor:/var/www/backend/vendor
        restart: on-failure
        ports:
            - "80:80"
        networks:
            - backend_app
        env_file:
            - docker/.env.nginx

volumes:
    backend_var:
    backend_vendor:
    gymek_data:

networks:
    backend_app:
